import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import NavMenu from "./components/NavMenu";

export const metadata = {
  title: "Izac Peterson",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-zinc-900 text-zinc-100">
      <body>
        <main className="flex">
          <NavMenu />
          <div className="pt-24 lg:pt-0 flex m-auto p-4">{children}</div>
        </main>
      </body>
    </html>
  );
}
